@startuml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2

!include DEVICONS/java.puml
!include DEVICONS/mysql.puml
!include DEVICONS/nodejs.puml
!include DEVICONS/angular.puml
!include DEVICONS2/apachekafka_original.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(usuario, "Usuario", "Usuário")

System_Boundary(contaantiga, "Conjunto") {
    Container_Ext(backend_app, "Backend REST ", "Spring Boot (Java)", $sprite="java" ,"API REST ")#Green
    ContainerDb(mariadb, "Banco de dados", "MariaDB", "Dados de créditos", $sprite="mysql")#Green
    ContainerQueue(broker, "Publisher", "Kafka", "Notificação para auditoria",$sprite="apachekafka_original") #Red
    Container(front_app, "Frontend", $sprite="angular", "Consulta créditos") #Green
    Container(adminer, "Adminer", $sprite="", "Visualizador do banco de dados") #Green
    Container(kafka_logger, "Kafka Logger", $sprite="", "Logger do kafka") #Green
}

BiRel(usuario, front_app, "Usa", "")

BiRel(front_app, backend_app, "Chama APIs", "HTTPS/JSON")


BiRel_D(kafka_logger, broker, "Notifica consultas", "Async")
Rel_R(backend_app, broker, "Lê topicos", "Async")
BiRel_L(backend_app, mariadb, "read")
BiRel_D(adminer, mariadb, "read")

@enduml