services:
  mariadb:
    image: mariadb:10.11
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - credito-network
    volumes:
      - mariadb_data_credito:/var/lib/mysql
    command: 
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
  adminer:
    image: adminer:latest
    container_name: adminer_web
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - credito-network
    depends_on:
      - mariadb
  credito-guide-backend:
    build: ./backend
    container_name: credito-guide-backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - credito-network
    environment:
      APP_ENVIRONMENT: ${ENVIRONMENT:-production}
      JAVA_OPTS: "-Xmx512m -Xms256m"
    env_file:
      - .env
    depends_on:
      - mariadb
networks:
  credito-network:
    driver: bridge
volumes:
  mariadb_data_credito:
    driver: local
    name: ${DB_VOLUME_NAME}