spring.application.name=credito-guide
management.endpoints.web.exposure.include=health
spring.jackson.serialization.indent_output=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true


logging.level.org.springdoc=DEBUG
