spring.application.name=credito-guide
management.endpoints.web.exposure.include=health
spring.jackson.serialization.indent_output=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true


logging.level.org.springdoc=DEBUG

# JPA (mesmo que você não use agora)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


# # PostgreSQL Database
# spring.datasource.url=jdbc:postgresql://creditos-postgres-teste:5432/${POSTGRES_DB}
spring.datasource.url=jdbc:${DB_JDBC}://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# spring.datasource.password=${POSTGRES_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari Connection Pool
# spring.datasource.hikari.connection-timeout=30000
# spring.datasource.hikari.maximum-pool-size=10
# spring.datasource.hikari.minimum-idle=5
# spring.datasource.hikari.idle-timeout=600000
# spring.datasource.hikari.max-lifetime=1800000
# spring.datasource.hikari.connection-test-query=SELECT 1
# spring.datasource.hikari.pool-name=CreditoHikariPool

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

logging.level.org.springframework.web.servlet.resource=ERROR
